services:
  dashboard-api:
    container_name: dashboard-api
    build: .
    ports:
      - "8085:8000"
    env_file:
      - .env
    environment:
      DB_TIME_ZONE: Europe/Moscow
    volumes:
      # Host path with mp3 files. Set AUDIO_DIR in .env
      - ${AUDIO_DIR:?set AUDIO_DIR}:/audio
      - ./app:/code/app
    restart: always
    networks:
      - mysql_default
    command: ["uvicorn", "main:app", "--app-dir", "app", "--reload", "--reload-dir", "app", "--host", "0.0.0.0", "--port", "8000", "--no-access-log"]

networks:
  mysql_default:
    external: true
